/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AddressApi,
  DocumentApi,
  HealthApi,
  NaturalPersonApi,
  ScreeningApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { ProoViDCustom } from "./client-custom";

export class ProoViD extends ProoViDCustom {
  readonly address: AddressApi;
  readonly document: DocumentApi;
  readonly health: HealthApi;
  readonly naturalPerson: NaturalPersonApi;
  readonly screening: ScreeningApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.address = new AddressApi(configuration);
    this.document = new DocumentApi(configuration);
    this.health = new HealthApi(configuration);
    this.naturalPerson = new NaturalPersonApi(configuration);
    this.screening = new ScreeningApi(configuration);
  }

}
