/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddNaturalPersonDataSaveResult } from './add-natural-person-data-save-result';
import { DocumentImages } from './document-images';
import { SumSubVerificationResponse } from './sum-sub-verification-response';

/**
 * 
 * @export
 * @interface AddNaturalPersonResponse
 */
export interface AddNaturalPersonResponse {
    /**
     * 
     * @type {number}
     * @memberof AddNaturalPersonResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AddNaturalPersonResponse
     */
    'clientReferenceId'?: string | null;
    /**
     * 
     * @type {DocumentImages}
     * @memberof AddNaturalPersonResponse
     */
    'documentImages'?: DocumentImages;
    /**
     * 
     * @type {AddNaturalPersonDataSaveResult}
     * @memberof AddNaturalPersonResponse
     */
    'dataSaveResponses'?: AddNaturalPersonDataSaveResult;
    /**
     * 
     * @type {SumSubVerificationResponse}
     * @memberof AddNaturalPersonResponse
     */
    'verifications'?: SumSubVerificationResponse;
}

