/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AddressRequest
 */
export interface AddressRequest {
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'referenceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'email'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddressRequest
     */
    'naturalPersonId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AddressRequest
     */
    'naturalPersonIndexId'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'surname'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'mobilePhone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'language'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddressRequest
     */
    'verificationLevel'?: number;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'document'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'street'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'streetNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'unit'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'district'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'region'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'zipCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'country'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    'fullAddress'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AddressRequest
     */
    'skipDocumentComparison'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AddressRequest
     */
    'validityPeriod'?: number;
}

