/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Asset } from './asset';
import { Associate } from './associate';
import { Field } from './field';
import { Media } from './media';
import { SourceNote } from './source-note';

/**
 * 
 * @export
 * @interface AmlRecord
 */
export interface AmlRecord {
    /**
     * 
     * @type {number}
     * @memberof AmlRecord
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'source'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'middleName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'gender'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AmlRecord
     */
    'status'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AmlRecord
     */
    'isDeath'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'dateOfBirth'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'placeOfBirth'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'urlReport'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'categories'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'notes'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'sanctionsReferences'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'officialLists'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'importanDates'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'otherNames'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'idNumbers'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'associates'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'images'?: Array<string> | null;
    /**
     * 
     * @type {Array<Associate>}
     * @memberof AmlRecord
     */
    'relatedPersons'?: Array<Associate> | null;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'name'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AmlRecord
     */
    'score'?: number;
    /**
     * 
     * @type {string}
     * @memberof AmlRecord
     */
    'entityType'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'filters'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'matchTypes'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'alternativeNames'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'sources'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AmlRecord
     */
    'types'?: Array<string> | null;
    /**
     * 
     * @type {Array<Asset>}
     * @memberof AmlRecord
     */
    'assets'?: Array<Asset> | null;
    /**
     * 
     * @type {Array<Media>}
     * @memberof AmlRecord
     */
    'media'?: Array<Media> | null;
    /**
     * 
     * @type {{ [key: string]: Array<Field>; }}
     * @memberof AmlRecord
     */
    'fields'?: { [key: string]: Array<Field>; } | null;
    /**
     * 
     * @type {{ [key: string]: SourceNote; }}
     * @memberof AmlRecord
     */
    'sourceNotes'?: { [key: string]: SourceNote; } | null;
}

