/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DocumentVerificationData
 */
export interface DocumentVerificationData {
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'middleName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'fullName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'documentNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'issueDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'expiredDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'dob'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'documentType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'countryBirth'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerificationData
     */
    'countryDocument'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DocumentVerificationData
     */
    'faceMatchConfidence'?: number | null;
}

