/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DocumentAddressResponse
 */
export interface DocumentAddressResponse {
    /**
     * 
     * @type {string}
     * @memberof DocumentAddressResponse
     */
    'street'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentAddressResponse
     */
    'streetNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentAddressResponse
     */
    'buildingName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentAddressResponse
     */
    'buildingNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentAddressResponse
     */
    'flatNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentAddressResponse
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentAddressResponse
     */
    'state'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentAddressResponse
     */
    'zipCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentAddressResponse
     */
    'country'?: string | null;
}

