/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Geolocation
 */
export interface Geolocation {
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'host'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'ip'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'rdns'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'asn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'isp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'countryName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'countryCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'regionName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'regionCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'postalCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'continentName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'continentCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'latitude'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'longitude'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'metroCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Geolocation
     */
    'timezone'?: string | null;
}

