/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GpsLocation
 */
export interface GpsLocation {
    /**
     * 
     * @type {number}
     * @memberof GpsLocation
     */
    'latitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof GpsLocation
     */
    'longitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof GpsLocation
     */
    'accuracy'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GpsLocation
     */
    'altitude'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GpsLocation
     */
    'altitudeAccuracy'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GpsLocation
     */
    'heading'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GpsLocation
     */
    'speed'?: string | null;
}

