/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Level
 */
export interface Level {
    /**
     * 
     * @type {number}
     * @memberof Level
     */
    'id'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Level
     */
    'status'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Level
     */
    'statusDescription'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Level
     */
    'steps'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Level
     */
    'errors'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Level
     */
    'declinedCodes'?: Array<string> | null;
}

