/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NaturalPersonELVRequest
 */
export interface NaturalPersonELVRequest {
    /**
     * 
     * @type {number}
     * @memberof NaturalPersonELVRequest
     */
    'naturalPersonIndexId'?: number;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'street'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'streetNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'unit'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'zipCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'district'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'region'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'country'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'mobile'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonELVRequest
     */
    'fullAddress'?: string | null;
}

