/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EGender } from './egender';
import { EStatus } from './estatus';
import { RejectLabelType } from './reject-label-type';

/**
 * 
 * @export
 * @interface NaturalPersonDocumentVerificationResponse
 */
export interface NaturalPersonDocumentVerificationResponse {
    /**
     * 
     * @type {EStatus}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'status'?: EStatus;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'comment'?: string | null;
    /**
     * 
     * @type {Array<RejectLabelType>}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'rejectLabels'?: Array<RejectLabelType> | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'dateOfBirth'?: string | null;
    /**
     * 
     * @type {EGender}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'gender'?: EGender;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'country'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'issuedDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'issueAuthority'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'firstIssuedDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'validUntil'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'number'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'additionalNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'mrzLine1'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'mrzLine2'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'mrzLine3'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'imageId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'additionalImageId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'creationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonDocumentVerificationResponse
     */
    'lastUpdatedDate'?: string;
}

