/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NaturalPersonDocumentRequest } from './natural-person-document-request';
import { NaturalPersonIdDocumentRequest } from './natural-person-id-document-request';

/**
 * 
 * @export
 * @interface NaturalPersonDocumentsRequest
 */
export interface NaturalPersonDocumentsRequest {
    /**
     * 
     * @type {NaturalPersonIdDocumentRequest}
     * @memberof NaturalPersonDocumentsRequest
     */
    'idDocument'?: NaturalPersonIdDocumentRequest;
    /**
     * 
     * @type {NaturalPersonDocumentRequest}
     * @memberof NaturalPersonDocumentsRequest
     */
    'addressDocument'?: NaturalPersonDocumentRequest;
}

