/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EGender } from './egender';
import { EScore } from './escore';
import { EStatus } from './estatus';
import { NaturalPersonAddressVerificationResponse } from './natural-person-address-verification-response';
import { NaturalPersonAmlVerificationResponse } from './natural-person-aml-verification-response';
import { NaturalPersonDocumentVerificationResponse } from './natural-person-document-verification-response';
import { NaturalPersonEconomicProfileResponse } from './natural-person-economic-profile-response';
import { NaturalPersonFaceVerificationResponse } from './natural-person-face-verification-response';
import { NaturalPersonOccupationResponse } from './natural-person-occupation-response';
import { NaturalPersonOtherSourceOfIncomeResponse } from './natural-person-other-source-of-income-response';
import { NaturalPersonOtherSourceOfWealthResponse } from './natural-person-other-source-of-wealth-response';
import { RejectLabelType } from './reject-label-type';

/**
 * 
 * @export
 * @interface NaturalPersonInfoResponse
 */
export interface NaturalPersonInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof NaturalPersonInfoResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'clientReferenceId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'creationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'lastUpdatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'deletionDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'taxId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'middleName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'legalName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'dateOfBirth'?: string | null;
    /**
     * 
     * @type {EGender}
     * @memberof NaturalPersonInfoResponse
     */
    'gender'?: EGender;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'countryBirth'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'countryResidence'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'countryMainBusiness'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'nationality'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'emailTwo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'mobilePhone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'mobilePhoneTwo'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof NaturalPersonInfoResponse
     */
    'automaticallyUpdateNPRisk'?: boolean | null;
    /**
     * 
     * @type {EScore}
     * @memberof NaturalPersonInfoResponse
     */
    'riskLevel'?: EScore;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'riskLevelJustification'?: string | null;
    /**
     * 
     * @type {EStatus}
     * @memberof NaturalPersonInfoResponse
     */
    'status'?: EStatus;
    /**
     * 
     * @type {Array<RejectLabelType>}
     * @memberof NaturalPersonInfoResponse
     */
    'rejectLabels'?: Array<RejectLabelType> | null;
    /**
     * 
     * @type {boolean}
     * @memberof NaturalPersonInfoResponse
     */
    'isFlagged'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonInfoResponse
     */
    'comments'?: string | null;
    /**
     * 
     * @type {NaturalPersonEconomicProfileResponse}
     * @memberof NaturalPersonInfoResponse
     */
    'economicProfile'?: NaturalPersonEconomicProfileResponse;
    /**
     * 
     * @type {NaturalPersonDocumentVerificationResponse}
     * @memberof NaturalPersonInfoResponse
     */
    'documentVerification'?: NaturalPersonDocumentVerificationResponse;
    /**
     * 
     * @type {NaturalPersonAddressVerificationResponse}
     * @memberof NaturalPersonInfoResponse
     */
    'addressVerification'?: NaturalPersonAddressVerificationResponse;
    /**
     * 
     * @type {NaturalPersonFaceVerificationResponse}
     * @memberof NaturalPersonInfoResponse
     */
    'faceVerification'?: NaturalPersonFaceVerificationResponse;
    /**
     * 
     * @type {NaturalPersonAmlVerificationResponse}
     * @memberof NaturalPersonInfoResponse
     */
    'screeningVerification'?: NaturalPersonAmlVerificationResponse;
    /**
     * 
     * @type {Array<NaturalPersonOtherSourceOfIncomeResponse>}
     * @memberof NaturalPersonInfoResponse
     */
    'otherSourcesOfIncome'?: Array<NaturalPersonOtherSourceOfIncomeResponse> | null;
    /**
     * 
     * @type {Array<NaturalPersonOtherSourceOfWealthResponse>}
     * @memberof NaturalPersonInfoResponse
     */
    'otherSourcesOfWealth'?: Array<NaturalPersonOtherSourceOfWealthResponse> | null;
    /**
     * 
     * @type {Array<NaturalPersonOccupationResponse>}
     * @memberof NaturalPersonInfoResponse
     */
    'industries'?: Array<NaturalPersonOccupationResponse> | null;
}

