/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentAddressResponse } from './document-address-response';
import { EStatus } from './estatus';
import { RejectLabelType } from './reject-label-type';

/**
 * 
 * @export
 * @interface NaturalPersonAddressVerificationResponse
 */
export interface NaturalPersonAddressVerificationResponse {
    /**
     * 
     * @type {EStatus}
     * @memberof NaturalPersonAddressVerificationResponse
     */
    'status'?: EStatus;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonAddressVerificationResponse
     */
    'comment'?: string | null;
    /**
     * 
     * @type {Array<RejectLabelType>}
     * @memberof NaturalPersonAddressVerificationResponse
     */
    'rejectLabels'?: Array<RejectLabelType> | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonAddressVerificationResponse
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonAddressVerificationResponse
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonAddressVerificationResponse
     */
    'issuedDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonAddressVerificationResponse
     */
    'imageId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonAddressVerificationResponse
     */
    'creationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonAddressVerificationResponse
     */
    'lastUpdatedDate'?: string;
    /**
     * 
     * @type {DocumentAddressResponse}
     * @memberof NaturalPersonAddressVerificationResponse
     */
    'address'?: DocumentAddressResponse;
}

