/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NaturalPerson
 */
export interface NaturalPerson {
    /**
     * 
     * @type {number}
     * @memberof NaturalPerson
     */
    'id'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NaturalPerson
     */
    'systemId'?: number;
    /**
     * 
     * @type {string}
     * @memberof NaturalPerson
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPerson
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPerson
     */
    'middleName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPerson
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof NaturalPerson
     */
    'countryOrigin'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPerson
     */
    'countryResidence'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPerson
     */
    'countryMainFunds'?: string | null;
}

