/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EMoneyRange } from './emoney-range';
import { EScore } from './escore';
import { ESourceOfIncomeAnswers } from './esource-of-income-answers';
import { ESourceOfWealthAnswers } from './esource-of-wealth-answers';
import { EWealthRange } from './ewealth-range';

/**
 * 
 * @export
 * @interface NaturalPersonEconomicProfileResponse
 */
export interface NaturalPersonEconomicProfileResponse {
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'mainBusinessActivities'?: string | null;
    /**
     * 
     * @type {EMoneyRange}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'sizeOfAnnualIncome'?: EMoneyRange;
    /**
     * 
     * @type {number}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'sizeOfAnnualIncomeMin'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'sizeOfAnnualIncomeMax'?: number | null;
    /**
     * 
     * @type {ESourceOfIncomeAnswers}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'mainSourceOfIncome'?: ESourceOfIncomeAnswers;
    /**
     * 
     * @type {EWealthRange}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'sizeOfWealth'?: EWealthRange;
    /**
     * 
     * @type {number}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'sizeOfWealthMin'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'sizeOfWealthMax'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'isHnwi'?: boolean;
    /**
     * 
     * @type {ESourceOfWealthAnswers}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'sourceOfWealth'?: ESourceOfWealthAnswers;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'expectedOriginOfOutgoingFunds'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'expectedOriginOfIncomingFunds'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'natureOfTransaction'?: string | null;
    /**
     * 
     * @type {EMoneyRange}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'anticipatedAccountTurnOver'?: EMoneyRange;
    /**
     * 
     * @type {number}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'anticipatedAccountTurnOverMin'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'anticipatedAccountTurnOverMax'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'purposeOfBusinessRelationship'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'industryNameOfHighestRisk'?: string | null;
    /**
     * 
     * @type {EScore}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'industryRiskOfHighestRisk'?: EScore;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'creationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof NaturalPersonEconomicProfileResponse
     */
    'lastUpdatedDate'?: string;
}

