/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Info } from './info';
import { VerificationData } from './verification-data';
import { VerificationResult } from './verification-result';

/**
 * 
 * @export
 * @interface ShuftiAddressDataResponse
 */
export interface ShuftiAddressDataResponse {
    /**
     * 
     * @type {Info}
     * @memberof ShuftiAddressDataResponse
     */
    'info'?: Info;
    /**
     * 
     * @type {string}
     * @memberof ShuftiAddressDataResponse
     */
    'reference'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShuftiAddressDataResponse
     */
    'event'?: string | null;
    /**
     * 
     * @type {Error}
     * @memberof ShuftiAddressDataResponse
     */
    'error'?: Error;
    /**
     * 
     * @type {string}
     * @memberof ShuftiAddressDataResponse
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShuftiAddressDataResponse
     */
    'country'?: string | null;
    /**
     * 
     * @type {VerificationData}
     * @memberof ShuftiAddressDataResponse
     */
    'verificationData'?: VerificationData;
    /**
     * 
     * @type {VerificationResult}
     * @memberof ShuftiAddressDataResponse
     */
    'verificationResult'?: VerificationResult;
    /**
     * 
     * @type {string}
     * @memberof ShuftiAddressDataResponse
     */
    'declinedReason'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ShuftiAddressDataResponse
     */
    'declinedCodes'?: Array<string> | null;
}

