/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SumSubAmlVerificationResponse } from './sum-sub-aml-verification-response';
import { SumSubDocumentVerificationVerificationResponse } from './sum-sub-document-verification-verification-response';

/**
 * 
 * @export
 * @interface SumSubVerificationResponse
 */
export interface SumSubVerificationResponse {
    /**
     * 
     * @type {string}
     * @memberof SumSubVerificationResponse
     */
    'creationDate'?: string;
    /**
     * 
     * @type {SumSubAmlVerificationResponse}
     * @memberof SumSubVerificationResponse
     */
    'screening'?: SumSubAmlVerificationResponse;
    /**
     * 
     * @type {SumSubDocumentVerificationVerificationResponse}
     * @memberof SumSubVerificationResponse
     */
    'idDocument'?: SumSubDocumentVerificationVerificationResponse;
    /**
     * 
     * @type {SumSubDocumentVerificationVerificationResponse}
     * @memberof SumSubVerificationResponse
     */
    'face'?: SumSubDocumentVerificationVerificationResponse;
    /**
     * 
     * @type {SumSubDocumentVerificationVerificationResponse}
     * @memberof SumSubVerificationResponse
     */
    'addressDocument'?: SumSubDocumentVerificationVerificationResponse;
}

