/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EStatus } from './estatus';
import { RejectLabelType } from './reject-label-type';

/**
 * 
 * @export
 * @interface SumSubDocumentVerificationVerificationResponse
 */
export interface SumSubDocumentVerificationVerificationResponse {
    /**
     * 
     * @type {EStatus}
     * @memberof SumSubDocumentVerificationVerificationResponse
     */
    'status'?: EStatus;
    /**
     * 
     * @type {string}
     * @memberof SumSubDocumentVerificationVerificationResponse
     */
    'comment'?: string | null;
    /**
     * 
     * @type {Array<RejectLabelType>}
     * @memberof SumSubDocumentVerificationVerificationResponse
     */
    'rejectLabels'?: Array<RejectLabelType> | null;
    /**
     * 
     * @type {string}
     * @memberof SumSubDocumentVerificationVerificationResponse
     */
    'creationDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof SumSubDocumentVerificationVerificationResponse
     */
    'verificationId'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SumSubDocumentVerificationVerificationResponse
     */
    'imageId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SumSubDocumentVerificationVerificationResponse
     */
    'additionalImageId'?: string | null;
}

