/*
Proovid Electronic Verification

Proovid API is a RESTful application that specializes in electronic verification (Proof of address and Proof of Identity) by employing an advanced risk-tiered approacch in combination with a smart Risk assessment system. <a href='docs/PROOVid_ELV.pdf' target='_blank'>More information</a> 

The version of the OpenAPI document: v1
Contact: info@proovid.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentImages } from './document-images';
import { SumSubVerificationResponse } from './sum-sub-verification-response';
import { UpdateNaturalPersonDocumentsDataSaveResult } from './update-natural-person-documents-data-save-result';

/**
 * 
 * @export
 * @interface UpdateNaturalPersonDocumentsResponse
 */
export interface UpdateNaturalPersonDocumentsResponse {
    /**
     * 
     * @type {number}
     * @memberof UpdateNaturalPersonDocumentsResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateNaturalPersonDocumentsResponse
     */
    'clientReferenceId'?: string | null;
    /**
     * 
     * @type {UpdateNaturalPersonDocumentsDataSaveResult}
     * @memberof UpdateNaturalPersonDocumentsResponse
     */
    'dataSaveResponses'?: UpdateNaturalPersonDocumentsDataSaveResult;
    /**
     * 
     * @type {SumSubVerificationResponse}
     * @memberof UpdateNaturalPersonDocumentsResponse
     */
    'verification'?: SumSubVerificationResponse;
    /**
     * 
     * @type {DocumentImages}
     * @memberof UpdateNaturalPersonDocumentsResponse
     */
    'documentImages'?: DocumentImages;
}

